DEVICE_PATH := device/trident/a25

# Architecture & Platform
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_VARIANT := cortex-a73
TARGET_BOARD_PLATFORM := mt6771
TARGET_SUPPORTS_64_BIT_APPS := true

# Partitions & Sizes
BOARD_BOOTIMAGE_PARTITION_SIZE := 35651584
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 35651584
BOARD_DTBOIMG_PARTITION_SIZE := 8388608
BOARD_FLASH_BLOCK_SIZE := 262144

# Boot Image Arguments
BOARD_KERNEL_BASE := 0x40000000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_MKBOOTIMG_ARGS := --header_version 2 --dtb $(DEVICE_PATH)/prebuilts/dtb
BOARD_INCLUDE_DTB_IN_BOOTIMG := true

# Prebuilt Kernel & DTBO
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilts/kernel
BOARD_KERNEL_IMAGE_NAME := kernel
TARGET_NO_KERNEL := true
BOARD_PREBUILT_DTBOIMAGE := $(DEVICE_PATH)/prebuilts/dtbo.img

# VINTF Manifest
DEVICE_MANIFEST_FILE := $(DEVICE_PATH)/configs/vintf/manifest.xml
DEVICE_MANIFEST_FRAGMENTS := \
	$(filter-out $(DEVICE_MANIFEST_FILE), $(wildcard $(DEVICE_PATH)/configs/vintf/*.xml))
PRODUCT_ENFORCE_VINTF_MANIFEST := false

# Dynamic Partitions
BOARD_USE_DYNAMIC_PARTITIONS := true
BOARD_SUPER_PARTITION_SIZE := 3758096384
BOARD_SUPER_PARTITION_GROUPS := main
BOARD_MAIN_SIZE := 3755999232
BOARD_MAIN_PARTITION_LIST := system product vendor odm

# Partition Sizes & File Systems
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1478144000
BOARD_VENDORIMAGE_PARTITION_SIZE := 671088640
BOARD_PRODUCTIMAGE_PARTITION_SIZE := 1547948032

BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_PRODUCTIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_HAS_LARGE_FILESYSTEM := true

TARGET_COPY_OUT_VENDOR := vendor
TARGET_COPY_OUT_PRODUCT := product

# Verified Boot (AVB)
BOARD_AVB_ENABLE := true
BOARD_AVB_MAKE_VBMETA_IMAGE_ARGS += --flags 0 --algorithm NONE

# SELinux & SEPolicy
BOARD_KERNEL_CMDLINE += androidboot.selinux=permissive
BOARD_SEPOLICY_VERS := 30.0
SEPOLICY_VERS := 30.0
BOARD_SEPOLICY_DISABLE_NEVERALLOWS := true
SELINUX_IGNORE_NEVERALLOWS := true
BUILD_SEPOLICY_VERSIONED_DEPS := false
BUILD_BROKEN_POLICIES := true
SEPOLICY_BUILD_FLATTENED_SEPOLICY := true

BOARD_VENDOR_SEPOLICY_DIRS += $(DEVICE_PATH)/sepolicy/vendor
SYSTEM_EXT_PRIVATE_SEPOLICY_DIRS += $(DEVICE_PATH)/sepolicy/private

# Build System Hacks
BUILD_BROKEN_ELF_PREBUILT_PRODUCT_COPY_FILES := true
